import 'package:schooler/classes/registration.dart';

List<String> vragenGOK = [
  'The family has received a school allowance in the 2019-2020 school year and/or in the 2020-2021 school year.',
  'The mother of the pupil has a diploma of secondary education or a study certificate of the second year of the third degree of the secondary education or an associated equivalent study certificate.'
];

List<String> vragenTN = [
  'At least a Dutch-language diploma of secondary education or an equivalent Dutch-language study certificate.',
  'A Dutch-language certificate of the second year of the third stage of secondary education or an equivalent Dutch-language certificate.',
  'Proof of at least sufficient knowledge of Dutch issued by Selor.',
  'Proof of that one of them has attended 9 years of regular education in Dutch-language primary and secondary education.',
  'Proof that one of them masters Dutch at at least level B2',
];

List<String> scholen = [
  'eerst',
  'tweede',
  'derde',
  'vierde',
  'A-Vision Onderwijsadviesbureau',
  'Adriaan Roland Holstschool po',
  'Aldoende Openbare Basisschool',
  'Algemene basisschool Comenius',
/*
  'Amalia-Astroschool',
  'Montessori Basisschool',
  'Anne Frank school',
  'M G Schmidt',
  'Archipel Scholen',
  'Aremberg Openbare School',
  'Arnhemse Montessorischool',
  'Augustinus Basisschool',
  'b.s. De Floriant',
  'Basisschool Aan de Bron',
  'Basisschool Antares',
  'Basisschool Arnhemse School Vereniging',
  'Basisschool Baardwijk',
  'Basisschool Coninxhof',
  'Basisschool Cosmicus',
  'Basisschool De Bron',
  'Basisschool De Lockaert',
  'Basisschool De Nijepoort',
  'Basisschool De Regenboog',
  'Basisschool De Voeëgelsjtang',
  'Basisschool De Wereldweide',
  'Basisschool KinderRijk',
  'basisschool Maurice Rose',
  'Basisschool Op de Tien Bunder',
  'Basisschool Rosa Boekdrukker',
  'Basisschool Sint Martinus',
  'Basisschool St. Joseph',
  'Basisschool St. Jozef',
  'basisschool Tangram',
  'Beurthonk',
  'Bijstere Basisschool Den',
  'Bikube Kantoortijdenschool',
  'Bos en Vaart OBS',
  'Bosseschool',
  'Branding',
  'brede Basisschool St. Lukas te Amsterdam',
  'BS De Kastanjelaar Milheeze',
  'Burg. Verschoorschool'
  */
];

List<Registration> regiList = [
  new Registration(
      voornaam: 'Elise',
      naam: 'Brabant',
      rijksNr: '97042025942',
      straat: 'Winkelstraat',
      huisNr: 15,
      busNr: '',
      postcode: 1500,
      gemeente: 'Halle',
      oVoornaam1: 'Felicien',
      oNaam1: 'Brabant',
      beroep1: 'Bakker',
      berStraat1: 'Bakkerstaat',
      berHuisNr1: 13,
      berBusNr1: '',
      berPostcode1: 1500,
      berGemeente1: 'Halle',
      oVoornaam2: 'Melina',
      oNaam2: 'Hangover',
      beroep2: 'Tandarts',
      berStraat2: 'Ziekelaan',
      berHuisNr2: 12,
      berBusNr2: '',
      berPostcode2: 1500,
      berGemeente2: 'Halle',
      vraagGOK: true,
      vraagTN: true),
  new Registration(
      voornaam: 'Sarah',
      naam: 'Leemans',
      rijksNr: '97042025942',
      straat: 'Winkelstraat',
      huisNr: 15,
      busNr: '',
      postcode: 1500,
      gemeente: 'Halle',
      oVoornaam1: 'Felicien',
      oNaam1: 'Brabant',
      beroep1: 'Bakker',
      berStraat1: 'Bakkerstaat',
      berHuisNr1: 13,
      berBusNr1: '',
      berPostcode1: 1500,
      berGemeente1: 'Halle',
      oVoornaam2: 'Melina',
      oNaam2: 'Hangover',
      beroep2: 'Tandarts',
      berStraat2: 'Ziekelaan',
      berHuisNr2: 12,
      berBusNr2: '',
      berPostcode2: 1500,
      berGemeente2: 'Halle',
      vraagGOK: true,
      vraagTN: true),
  new Registration(
      voornaam: 'Tommy',
      naam: 'Pokers',
      rijksNr: '97042025942',
      straat: 'Winkelstraat',
      huisNr: 15,
      busNr: '',
      postcode: 1500,
      gemeente: 'Halle',
      oVoornaam1: 'Felicien',
      oNaam1: 'Brabant',
      beroep1: 'Bakker',
      berStraat1: 'Bakkerstaat',
      berHuisNr1: 13,
      berBusNr1: '',
      berPostcode1: 1500,
      berGemeente1: 'Halle',
      oVoornaam2: 'Melina',
      oNaam2: 'Hangover',
      beroep2: 'Tandarts',
      berStraat2: 'Ziekelaan',
      berHuisNr2: 12,
      berBusNr2: '',
      berPostcode2: 1500,
      berGemeente2: 'Halle',
      vraagGOK: true,
      vraagTN: true),
  new Registration(
      voornaam: 'Ash',
      naam: 'Ketchum',
      rijksNr: '97042025942',
      straat: 'Winkelstraat',
      huisNr: 15,
      busNr: '',
      postcode: 1500,
      gemeente: 'Halle',
      oVoornaam1: 'Felicien',
      oNaam1: 'Brabant',
      beroep1: 'Bakker',
      berStraat1: 'Bakkerstaat',
      berHuisNr1: 13,
      berBusNr1: '',
      berPostcode1: 1500,
      berGemeente1: 'Halle',
      oVoornaam2: 'Melina',
      oNaam2: 'Hangover',
      beroep2: 'Tandarts',
      berStraat2: 'Ziekelaan',
      berHuisNr2: 12,
      berBusNr2: '',
      berPostcode2: 1500,
      berGemeente2: 'Halle',
      vraagGOK: true,
      vraagTN: true),
  new Registration(
      voornaam: 'Bruce',
      naam: 'Wayne',
      rijksNr: '97042025942',
      straat: 'Winkelstraat',
      huisNr: 15,
      busNr: '',
      postcode: 1500,
      gemeente: 'Halle',
      oVoornaam1: 'Felicien',
      oNaam1: 'Brabant',
      beroep1: 'Bakker',
      berStraat1: 'Bakkerstaat',
      berHuisNr1: 13,
      berBusNr1: '',
      berPostcode1: 1500,
      berGemeente1: 'Halle',
      oVoornaam2: 'Melina',
      oNaam2: 'Hangover',
      beroep2: 'Tandarts',
      berStraat2: 'Ziekelaan',
      berHuisNr2: 12,
      berBusNr2: '',
      berPostcode2: 1500,
      berGemeente2: 'Halle',
      vraagGOK: true,
      vraagTN: true),
  new Registration(
      voornaam: 'Micheal',
      naam: 'Jackson',
      rijksNr: '97042025942',
      straat: 'Winkelstraat',
      huisNr: 15,
      busNr: '',
      postcode: 1500,
      gemeente: 'Halle',
      oVoornaam1: 'Felicien',
      oNaam1: 'Brabant',
      beroep1: 'Bakker',
      berStraat1: 'Bakkerstaat',
      berHuisNr1: 13,
      berBusNr1: '',
      berPostcode1: 1500,
      berGemeente1: 'Halle',
      oVoornaam2: 'Melina',
      oNaam2: 'Hangover',
      beroep2: 'Tandarts',
      berStraat2: 'Ziekelaan',
      berHuisNr2: 12,
      berBusNr2: '',
      berPostcode2: 1500,
      berGemeente2: 'Halle',
      vraagGOK: true,
      vraagTN: true)
];
