import 'package:schooler/classes/registration.dart';
import 'package:schooler/classes/school.dart';

List<String> vragenGOK = [
  'The family has received a school allowance in the 2019-2020 school year and/or in the 2020-2021 school year.',
  'The mother of the pupil has a diploma of secondary education or a study certificate of the second year of the third degree of the secondary education or an associated equivalent study certificate.'
];

List<String> vragenTN = [
  'At least a Dutch-language diploma of secondary education or an equivalent Dutch-language study certificate.',
  'A Dutch-language certificate of the second year of the third stage of secondary education or an equivalent Dutch-language certificate.',
  'Proof of at least sufficient knowledge of Dutch issued by Selor.',
  'Proof of that one of them has attended 9 years of regular education in Dutch-language primary and secondary education.',
  'Proof that one of them masters Dutch at at least level B2',
];

List<String> scholen = [

  'A-Vision Onderwijsadviesbureau',
  'Adriaan Roland Holstschool po',
  'Aldoende Openbare Basisschool',
  'Algemene basisschool Comenius',

  'Amalia-Astroschool',
  'Montessori Basisschool',
  'Anne Frank school',
  'M G Schmidt',
  'Archipel Scholen',
  'Aremberg Openbare School',
  'Arnhemse Montessorischool',
  'Augustinus Basisschool',
  'b.s. De Floriant',
  'Basisschool Aan de Bron',
  'Basisschool Antares',
  'Basisschool Arnhemse School Vereniging',
  'Basisschool Baardwijk',
  'Basisschool Coninxhof',
  'Basisschool Cosmicus',
  'Basisschool De Bron',
  'Basisschool De Lockaert',
  'Basisschool De Nijepoort',
  'Basisschool De Regenboog',
  'Basisschool De Voeëgelsjtang',
  'Basisschool De Wereldweide',
  'Basisschool KinderRijk',
  'basisschool Maurice Rose',
  'Basisschool Op de Tien Bunder',
  'Basisschool Rosa Boekdrukker',
  'Basisschool Sint Martinus',
  'Basisschool St. Joseph',
  'Basisschool St. Jozef',
  'basisschool Tangram',
  'Beurthonk',
  'Bijstere Basisschool Den',
  'Bikube Kantoortijdenschool',
  'Bos en Vaart OBS',
  'Bosseschool',
  'Branding',
  'brede Basisschool St. Lukas te Amsterdam',
  'BS De Kastanjelaar Milheeze',
  'Burg. Verschoorschool'

];

List<SchoolObject> scholen2 = [


  SchoolObject(naam : 'Atheneum  for Business', adres : 'Toverfluitstraat 19-21, 1080 Sint-Jans-Molenbeek', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Campus Kompas', adres : 'Gallaitstraat 58-64, 1030 Schaarbeek', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Don Bosco Technisch Instituut', adres : 'Guldendallaan 90, 1150 Sint-Pieters-Woluwe', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Freinetschool Keerpunt Molenbeek', adres : 'Delaunoystraat 58, 1080 Sint-Jans-Molenbeek', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Freinetschool Keerpunt Vorst', adres : 'de Haveskerckelaan 25, 1190 Vorst', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Atheneum Anderlecht', adres : 'Sint-Guidostraat 73, 1070 Anderlecht', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Atheneum Brussel', adres : 'Moutstraat 24, 1000 Brussel', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Atheneum Comenius', adres : 'Félix Vande Sandestraat 11, 1081 Koekelberg', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Atheneum Emanuel Hiel Schaarbeek-Evere', adres : 'Charles Gilisquetlaan 34, 1030 Schaarbeek', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Atheneum Etterbeek', adres : 'Edmond Mesenslaan 2, 1040 Etterbeek', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Atheneum Unescoschool Koekelberg', adres : 'Klein Berchemstraat 1, 1081 Koekelberg', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'COOVI Secundair Onderwijs', adres : 'Emile Grysonlaan 45, 1070 Anderlecht', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Kunsthumaniora Brussel', adres : 'Chrysantenstraat 26, 1020 Laken', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'meertalig atheneum Sint-Pieters-Woluwe', adres : 'Grote Prijzenlaan 59, 1150 Sint-Pieters-Woluwe', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'middenschool en atheneum Kalevoet', adres : 'Nekkersgatlaan 17, 1180 Ukkel', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Technisch atheneum Jette', adres : 'Léon Theodorstraat 80, 1090 Jette', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Technisch atheneum Victor Hortaschool Evere', adres : 'Oudstrijderslaan 200, 1140 Evere', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Technisch atheneum Zavelenberg', adres : 'Oscar Ruelensplein 13, 1082 Sint-Agatha-Berchem', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Hoofdstedelijk Atheneum Karel Buls', adres : 'Bonekruidlaan 88, 1020 Laken', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Hoofdstedelijk Instituut Anneessens-Funck', adres : 'Groot Eiland 39, 1000 Brussel', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Imelda-Instituut', adres : 'Picardstraat 170, 1080 Sint-Jans-Molenbeek', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Jan-van-Ruusbroeckollege', adres : 'Forumlaan 4, 1020 Laken', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Lucernacollege Campus Innova', adres : 'Industrielaan 31, 1070 Anderlecht', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Lutgardiscollege', adres : 'De Wahalaan 11, 1160 Oudergem', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Maria Assumptalyceum', adres : 'Stalkruidlaan 9, 1020 Laken', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Maria-Boodschaplyceum', adres : 'Moutstraat 19-23, 1000 Brussel', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Mater Dei-Instituut', adres : 'Luchtvaartlaan 70, 1150 Sint-Pieters-Woluwe', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Middelbare Steinerschool Brussel', adres : 'Priemstraat 53 bus 222, 1000 Brussel', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Regina Pacisinstituut', adres : 'Magnolialaan 2, 1020 Laken', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Sint-Guido-Instituut', adres : 'Dokter Jacobsstraat 67, 1070 Anderlecht', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Sint-Jan Berchmanscollege', adres : 'Ursulinenstraat 4, 1000 Brussel', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Sint-Jozefscollege', adres : 'Woluwelaan 20, 1150 Sint-Pieters-Woluwe', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Sint-Lukas Kunsthumaniora', adres : 'Groenstraat 156, 1030 Schaarbeek', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Sint-Niklaasinstituut', adres : 'Bergense Steenweg 1421, 1070 Anderlecht', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Sint-Pieterscollege', adres : 'Léon Theodorstraat 167, 1090 Jette', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Tienerschool Anderlecht', adres : 'Ninoofse Steenweg 369, 1070 Anderlecht', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Atheneum  for Business', adres : 'Toverfluitstraat 19-21, 1080 Sint-Jans-Molenbeek', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Campus Kompas', adres : 'Gallaitstraat 58-64, 1030 Schaarbeek', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Don Bosco Technisch Instituut', adres : 'Guldendallaan 90, 1150 Sint-Pieters-Woluwe', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'COOVI Secundair Onderwijs', adres : 'Emile Grysonlaan 1, 1070 Anderlecht', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Kalevoet', adres : 'Nekkersgatlaan 17, 1180 Ukkel', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Technisch atheneum Victor Hortaschool Evere', adres : 'Oudstrijderslaan 200, 1140 Evere', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Technisch atheneum Jette', adres : 'Léon Theodorstraat 80, 1090 Jette', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Technisch atheneum Zavelenberg', adres : 'Oscar Ruelensplein 13, 1082 Sint-Agatha-Berchem', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Hoofdstedelijk Instituut Anneessens-Funck', adres : 'Groot Eiland 39, 1000 Brussel', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Imelda-Instituut', adres : 'Picardstraat 170, 1080 Sint-Jans-Molenbeek', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Maria Assumptalyceum', adres : 'Stalkruidlaan 9, 1020 Laken', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Regina Pacisinstituut', adres : 'Magnolialaan 2, 1020 Laken', type : 'Secundair onderwijs'),
  SchoolObject(naam : 'Sint-Guido-Instituut', adres : 'Verheydenstraat 39, 1070 Anderlecht', type : 'Secundair onderwijs'),
  SchoolObject(naam: 'De Kleurdoos Brussel', adres : 'Moutstraat 24, 1000 Brussel', type : 'basisonderwijs'),
  SchoolObject(naam: 'De Kleurdoos Brussel', adres : 'Vaartstraat 24, 1000 Brussel', type : 'basisonderwijs'),
  SchoolObject(naam: "'t Plant'zoentje Laken", adres : 'Karel Bogaerdstraat 4, 1020 Brussel', type : 'basisonderwijs'),
  SchoolObject(naam: 'Schaarbeek Hendrik Conscience', adres : 'Gustave Latinislaan 94, 1030 Schaarbeek', type : 'basisonderwijs'),
  SchoolObject(naam: 'Atheneum Etterbeek', adres : 'Edmond Mesenslaan 2, 1040 Etterbeek', type : 'basisonderwijs'),
  SchoolObject(naam: 'De Wimpel Elsene', adres : 'Cansstraat 14, 1050 Elsene', type : 'basisonderwijs'),
  SchoolObject(naam: 'De Wimpel Elsene', adres : 'Washingtonstraat 35, 1050 Elsene', type : 'basisonderwijs'),
  SchoolObject(naam: 'De Wimpel Elsene', adres : 'Kroonlaan 13, 1050 Elsene', type : 'basisonderwijs'),
  SchoolObject(naam: 'De Bron', adres : 'Bronstraat 86A, 1060 Sint-Gillis', type : 'basisonderwijs'),
  SchoolObject(naam: 'De Goudenregen', adres : 'Frans Vervaeckstraat 47, 1083 Ganshoren', type : 'basisonderwijs'),
  SchoolObject(naam: 'Unescoschool Koekelberg', adres : 'Klein-Berchemstraat 1, 1081 Koekelberg', type : 'basisonderwijs'),
  SchoolObject(naam: 'Zavelberg Sint-Agatha-Berchem', adres : 'Oscar Ruelensplein 13, 1082 Sint-Agatha-Berchem', type : 'basisonderwijs'),
  SchoolObject(naam: 'Zavelberg Sint-Agatha-Berchem', adres : 'Openveldstraat 110, 1082 Sint-Agatha-Berchem', type : 'basisonderwijs'),
  SchoolObject(naam: 'Katoba Maria Boodschap Brussel', adres : 'Vlaamsesteenweg 155, 1000 Brussel', type : 'basisonderwijs'),
  SchoolObject(naam: 'Sint-Joris', adres : 'Cellebroersstraat 16, 1000 Brussel', type : 'basisonderwijs'),
  SchoolObject(naam: 'Sint-Joris', adres : 'Nieuwland 194, 1000 Brussel', type : 'basisonderwijs'),
  SchoolObject(naam: 'Sint-Ursula', adres : 'Dieudonné Lefèvrestraat 41, 1020 Brussel', type : 'basisonderwijs'),
  SchoolObject(naam: 'Sint-Albert', adres : 'Haeckstraat 61_1, 1080 Sint-Jans-Molenbeek', type : 'basisonderwijs'),
  SchoolObject(naam: 'Regenboog', adres : 'Ulensstraat 83, 1080 Sint-Jans-Molenbeek', type : 'basisonderwijs'),
  SchoolObject(naam: 'Heilige Familie Schaarbeek', adres : 'Helmetsesteenweg 216, 1030 Schaarbeek', type : 'basisonderwijs'),
  SchoolObject(naam: 'Boodschap', adres : 'Jan Stobbaertslaan 58, 1030 Schaarbeek', type : 'basisonderwijs'),
  SchoolObject(naam: 'Maria Schaarbeek', adres : 'Rubensstraat 108, 1030 Schaarbeek', type : 'basisonderwijs'),
  SchoolObject(naam: 'Champagnat', adres : 'Richard Vandeveldestraat 4, 1030 Schaarbeek', type : 'basisonderwijs'),
  SchoolObject(naam: 'Ten Nude', adres : 'John Waterloo Wilsonstraat 21, 1000 Brussel', type : 'basisonderwijs'),
  SchoolObject(naam: 'Lutgardis', adres : 'Generaal Fivéstraat 42, 1040 Etterbeek', type : 'basisonderwijs'),
  SchoolObject(naam: 'Lutgardis Elsene', adres : 'Emile de Becolaan 57, 1050 Elsene', type : 'basisonderwijs'),
  SchoolObject(naam: 'Sint-Gillis', adres : 'Fernand Bernierstraat 16, 1060 Sint-Gillis', type : 'basisonderwijs'),
  SchoolObject(naam: 'Voorzienigheid', adres : 'Georges Moreaustraat 104, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'R. Van Belle', adres : 'Itterbeekse Laan 550, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Sint-Pieter', adres : 'Dokter Jacobsstraat 49, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Veeweide', adres : 'Veeweidestraat 82, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Veeweide', adres : 'Veeweidestraat 80, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Goede Lucht', adres : 'Séverineplein 1A, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Goede Lucht', adres : 'Demosthenesstraat 231, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Goede Lucht', adres : 'Séverineplein 1, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'De Vijvers', adres : 'Pierre Longinstraat 1, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'De Vijvers', adres : 'Marius Renardlaan 5, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Dertien', adres : 'Wayezstraat 56, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Dertien', adres : 'Doverstraat 25, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Het Rad', adres : 'Asterhoek 6, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Het Rad', adres : 'Guillaume Melckmanslaan 18b, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Regina Assumpta', adres : 'Adolphe Willemynsstraat 213, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Sint-Guido', adres : 'Dokter Jacobsstraat 67, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'Instituut Maria Onbevlekt', adres : 'Resedastraat 61, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'De Groene School', adres : 'Bloeistraat 41, 1070 Anderlecht', type : 'basisonderwijs'),
  SchoolObject(naam: 'De Groene School', adres : 'Ninoofse Steenweg 369, 1070 Anderlecht', type : 'basisonderwijs')
];

